# Generated by Django 4.2.3 on 2023-07-20 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discription',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
